version: "3"
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    volumes:
      - ./app:/app


